Replace tabs with spaces

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,10 +9,10 @@
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+    # Initial commit: diff against an empty tree object
+    against=$(git hash-object -t tree /dev/null)
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -25,13 +25,13 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
+    cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -42,19 +42,19 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+    exit 1
 fi
 REPO_TOPLEVEL=$(git rev-parse --show-toplevel)
 ASTYLE=astyle
 ASTYLEOPTIONS="$REPO_TOPLEVEL/astyle.options"
 
 case `$ASTYLE --version 2> /dev/null` in
-	Artistic*)
-		;;
-	default)
-		echo "astyle not found. Install it to continue."
-		exit 1
-		;;
+    Artistic*)
+        ;;
+    default)
+        echo "astyle not found. Install it to continue."
+        exit 1
+        ;;
 esac
 
 
@@ -63,10 +63,10 @@ files=$(git diff-index --diff-filter=ACMR --name-only -r --cached $against -- | 
 for file in $files; do
     x=`echo $file`
     if test "x$x" != "x"; then
-		# Remove trailing spaces
+        # Remove trailing spaces
         sed -i 's/[[:space:]]*$//' $file
 
-		$ASTYLE $ASTYLEOPTIONS $file
+        $ASTYLE $ASTYLEOPTIONS $file
         git add $file
     fi
 done
